Make activeRequests readonly so it can't ever be null?
Attempting to fix strangeg CI failure:
```

7) dart test debugger
       "before each" hook: activate helloWorldTestMainFile for "runs a Dart test script to completion":
     TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at Object.cancelAllRequests [as cancelAllAnalysisRequests] (C:\projects\dart-code\src\services\stdio_service.ts:6:87)
      at Object.<anonymous> (C:\projects\dart-code\test\helpers.ts:109:9)
      at Generator.next (<anonymous>)
      at fulfilled (C:\projects\dart-code\out\test\helpers.js:4:58)
      at <anonymous>
```